#!/bin/bash

# Script to stop all jobs immediately in the MainJob_dir directory. 
#   (runs scancel on their job id) 
#---------------------------------

DIR="MainJob_dir"

# Check for existing directories: 
if [ "$(ls -A $DIR)" ]; then

 if [ -f Setup_and_Config ]; 
 then
   . Setup_and_Config/master_config_file
 fi 

echo -e "\n Jobs stopping.  \n Simulations currently running in $DIR will be terminated: \n" 
 sleep 1
 if [ -f .dir_list.txt ]; 
 then 
   y=$(cat .dir_list.txt) 
 else 
  echo -e " Can't see official job directory list: .dir_list.txt " 
  echo -e " Did you set up properly?  Exiting "
  exit 
 fi 
 
cd $DIR
for i in $y
# --find current_job_id 
do
  cd $i

  if [ -f .current_job_id.txt ];

  then
    j=$(cat .current_job_id.txt | tail -n 1  )

    scancel $j
    echo -e " Sent scancel command for job id  $j in directory $DIR/$i "
    echo -e "M:terminated " >.job_status
   else

    echo -e " No job appears to be running in directory $DIR/$i"
 fi   
  cd ../
  sleep 0.05
done

else
 echo -e  "\n There are no job directories in $DIR to stop jobs! \n" 

fi


